export const kanjiList = [
    {id: 0,
    character: '日',
    onReading: 'ニチ、ジツ',
    kunReading: 'ひ、び、か',
    meaning: 'Day, Sun',
    },  
    {id: 1,
    character: '一',
    onReading: 'イチ',
    kunReading: 'ひと',
    meaning: 'One, 1',
    },
    {id: 2,
    character: '国',
    onReading: 'コク',
    kunReading: 'くに',
    meaning: 'Country',
    },
    {id: 3,
    character: '人',
    onReading: 'ジン、ニン',
    kunReading: 'ひと',
    meaning: 'Person',
    },
    {id: 4,
    character: '年',
    onReading: 'ネン',
    kunReading: 'とし',
    meaning: 'Year (counter)',
    },
    {id: 5,
    character: '大',
    onReading: 'ダイ、タイ',
    kunReading: 'おお',
    meaning: 'Large, Big',
    },
    {id: 6,
    character: '十',
    onReading: 'ジュウ',
    kunReading: 'とう',
    meaning: 'Ten, 10',
    },
    {id: 7,
    character: '出',
    onReading: 'シュツ、スイ',
    kunReading: 'で、だ、い',
    meaning: 'Exit, Leave',
    },
    {id: 8,
    character: '二',
    onReading: 'ニ、ジ',
    kunReading: 'ふた',
    meaning: 'Two, 2',
    },
    {id: 9,
    character: '本',
    onReading: 'ホン',
    kunReading: 'もと',
    meaning: 'Book, present, true, counter for long cylindrical things',
    },
    {id: 10,
    character: '中',
    onReading: 'チュウ',
    kunReading: 'なか、うち、あた',
    meaning: 'In, Inside, Middle, Mean, Center',
    },
    {id: 11,
    character: '長',
    onReading: 'チョウ',
    kunReading: 'なが、おさ',
    meaning: 'Long, Lead, Superior, Senior',
    },
    {id: 12,
    character: '三',
    onReading: 'サン',
    kunReading: 'み',
    meaning: 'Three, 3',
    },
    {id: 13,
    character: '時',
    onReading: 'ジ',
    kunReading: 'とき、どき',
    meaning: 'Time',
    },
    {id: 14,
    character: '行',
    onReading: 'コウ、ギョウ、アン',
    kunReading: 'い、ゆ、おこな',
    meaning: 'Going, Journey, Carry Out, Line, Row',
    },
    {id: 15,
    character: '見',
    onReading: 'ケン',
    kunReading: 'み',
    meaning: 'See, Hopes, Chances, Idea, Opinion',
    },
    {id: 16,
    character: '月',
    onReading: 'ゲツ、ガツ',
    kunReading: 'つき',
    meaning: 'Month, Moon',
    },
    {id: 17,
    character: '分',
    onReading: 'ブン、フン、ブ',
    kunReading: 'わ',
    meaning: 'Part, Minute of Time, Understand',
    },
    {id: 18,
    character: '後',
    onReading: 'ゴ、コウ',
    kunReading: 'のち、うし、あと',
    meaning: 'Behind, Back, Later',
    },
    {id: 19,
    character: '前',
    onReading: 'ゼン',
    kunReading: 'まえ',
    meaning: 'In Front, Before',
    },
    {id: 20,
    character: '生',
    onReading: 'セイ、ショウ',
    kunReading: 'い、う、お、は、なま',
    meaning: 'Life, Genuine, Birth',
    },
    {id: 21,
    character: '五',
    onReading: 'ゴ',
    kunReading: 'いつ',
    meaning: 'Five, 5',
    },
    {id: 22,
    character: '間',
    onReading: 'カン、ケン',
    kunReading: 'あいだ、ま、あい',
    meaning: 'Interval, Space',
    },
    {id: 23,
    character: '上',
    onReading: 'ジョウ、ショウ、シャン',
    kunReading: 'うえ、うわー、かみ、あ、のぼ、たてまつ',
    meaning: 'Above, Up',
    },
    {id: 24,
    character: '東',
    onReading: 'トウ',
    kunReading: 'ひがし',
    meaning: 'East',
    },
    {id: 25,
    character: '四',
    onReading: 'シ',
    kunReading: 'よ、よん',
    meaning: 'Four, 4',
    },
    {id: 26,
    character: '今',
    onReading: 'コン、キン',
    kunReading: 'いま',
    meaning: 'Now, The Present',
    },
    {id: 27,
    character: '金',
    onReading: 'コン、キン、ゴン',
    kunReading: 'かね、かな、がね',
    meaning: 'Gold, Money',
    },
    {id: 28,
    character: '九',
    onReading: 'キュウ、ク',
    kunReading: 'ここの',
    meaning: 'Nine, 9',
    },
    {id: 29,
    character: '入',
    onReading: 'ニュウ',
    kunReading: 'い、はい',
    meaning: 'Enter, Insert',
    },
    {id: 30,
    character: '学',
    onReading: 'ガク',
    kunReading: 'まな',
    meaning: 'Study, Learning, Science',
    },
    {id: 31,
    character: '高',
    onReading: 'コウ',
    kunReading: 'たか',
    meaning: 'Tall, High, Expensive',
    },
    {id: 32,
    character: '円',
    onReading: 'エン',
    kunReading: 'まる',
    meaning: 'Circle, Yen, Round',
    },
    {id: 33,
    character: '子',
    onReading: 'シ、ス、ツ',
    kunReading: 'こ、ね',
    meaning: 'Child',
    },
    {id: 34,
    character: '外',
    onReading: 'ガイ、ゲ',
    kunReading: 'そと、ほか、はず、と',
    meaning: 'Outside',
    },
    {id: 35,
    character: '八',
    onReading: 'ハチ',
    kunReading: 'や、よう',
    meaning: 'Eight, 8',
    },
    {id: 36,
    character: '六',
    onReading: 'ロク',
    kunReading: 'む、むい',
    meaning: 'Six, 6',
    },
    {id: 37,
    character: '下',
    onReading: 'カ、ゲ',
    kunReading: 'した、しも、もと、さ、くだ、お',
    meaning: 'Below, Down, Descend, Give, Low, Inferior',
    },
    {id: 38,
    character: '来',
    onReading: 'ライ、タイ',
    kunReading: 'いき',
    meaning: 'Come, Due, Next, Cause, Become',
    },
    {id: 39,
    character: '気',
    onReading: 'キ、ケ',
    kunReading: 'いき',
    meaning: 'Spirit, Mind, Air, Atmosphere, Mood',
    }
    
    ]